version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
  core-api:
    build: .
    image: core-api
    container_name: core-api-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "80:8080"
#    volumes:
#     Example of your path: /home/user/Downloads
#        - your_path:/usr/app/logs
    links:
    - postgres