server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    use-legacy-processing: false

logging:
  level:
    ROOT: INFO
    ru.sber: DEBUG
    org.springframework: INFO