version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
  core-api:
    image: app
    container_name: core-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
    - postgres